### PR TITLE
Validate the length of text fields of each slots.

### PR DESCRIPTION
**Pull request by steka**
Make sure that the length of the concatenation of the fields (with NUL character separation) don't go beyond maximum length.
Instead of the previous way that just limited the length of the info field.

It also increase the visibility of the blue marking of each FX style slot, to make it easier to see.

### CODE REVIEW

**Comment by randomouscrap98** [comment]
Hey, thank you for the work, and for the interest in the project! I've seen you make changes to Mr.Blinky's python utilities, I'm grateful that you're taking a look at this one too!

So as for the color, it's a bit too dark for me, it makes the metadata very hard to read. I also have to contend with other operating systems who don't necessarily have the text render pure black. I've tried out several colors on my end, and I think this color may suite both our needs, it's a lot more noticeable than before but both light mode and dark mode are legible: `rgba(0,150,255,0.45)`. It's a lot brighter of a color so it's both more noticeable at a glance but also easy to read black text on it. And in dark mode, it's transparent enough to make it dark enough for the white text to shine through. Try it out and see what you think.

As for the max length stuff, while I do agree that having something more exact is better and I like the idea of your solution, I have a couple problems with it:
* In use, even I am confused whether the input is red because I put a bad character in it or what. There's no indication that I've "gone over the length", everything just turns red.
* When I load an arduboy file with information that's too long, everything also turns red. While this could be desired in some cases, it also is confusing for people. Did I load a bad arduboy file? No, it's just too long.
* I don't think truncating information that isn't even displayed or used inside the cart is worthy of a UI-level blaring red alert. I don't even do that for faulty carts, you instead get an error during compilation (like if there's not enough categories). It's an uneven UI experience
* I still want some kind of limit on the info field for my own purposes. I don't think that field should be allowed to be as long as you want; the title is SIGNIFICANTLY more important, I don't want anyone even thinking of changing the title, which your system may push people to do
* The red still shows up on the arduboy package creator, which I think isn't necessary. You can put as much data as you want in an arduboy package, I won't truncate it (other than info, which I still do want to truncate in arduboy packages so people at least have some idea they shouldn't go overboard)

I'm sorry for the big long list of complaints, I really do appreciate the modification. I just have a certain desire for the UI and I think this clashes with it. I do think we could improve on alerting the users to the 190 character limit, since it's not really stated anywhere, but I don't like this solution. If you come up with something else, let me know, but (a) I want to keep the 175 character limit, (b) the solution should make it obvious that what they've done wrong is gone over the 190 character limit (c) it shouldn't be seen as an "error level" event (which I count 'red' as), since the compilation doesn't stop you at all (d) it should not show up in the arduboy package editor. The last one is easy, you just check the mode for "all" and don't do whatever it is you want to do. Also consider that when loading an arduboy package, they could load multiple at one time and I don't really want to spam them with alerts or errors, especially because this truncation isn't really a big deal and the only thing that ever gets truncated is the info anyway.

**Comment by randomouscrap98** [comment]
Here, I've implemented something very similar to what you have here, just in the way I would like it to work. Let me know if it's good for you: https://github.com/randomouscrap98/arduboy_toolset/commit/bd21a8a450d77adf7679fea29d032b9b3933b3a4

I updated the FX color to be the one I mentioned earlier, and when you go over the total limit, I warn specifically on the info field, since it is the one to be truncated 99.99% of the time (literally; who is going to make a title + version + developer section THAT long such that it might truncate more?). Instead of making the whole input red, I just make the outline red and only for info, which is less harsh. I also add a tooltip so people can inspect the input and get more info about what's going on.

**Comment by randomouscrap98** [comment]
Agh I only just now realized after all this time on github that it's probably bad etiquette to make changes on main instead of the pull request, since it doesn't let you get marked as the contributor. I'm really sorry... I didn't mean to overshadow your contributions. If you make another modification in the future, I'll make sure to suggest changes on the pull request instead of reimplementing them on the main branch.

**Comment by steka** [comment]
That looks good, you just forgot to remove the no longer needed hard limit of the info field. I have merged in your implementation into this PR, so the only thing left is the removal of that hard limit.
So you now have a chance to redeem your "bad etiquette" :-)

**Comment by randomouscrap98** [comment]
Thank you again for your contributions 💙

**Pull request merged**
